### ISSUE TITLE
It's stuck after inputing my notes path

### ISSUE THREAD

**Issue by beviz** [connertennery/Notion-to-Obsidian-Converter#21]
```bash
$ node main
Notion Export Path:
/Users/bevis/Downloads/Export-3c2c8378-eb74-4a84-b82b-1a8ca3706768
```

No other logs, Ctrl + C or D doesn't work.

**Comment by beviz** [comment]
If it's working correctly, only needs more time to run. Could you please print more logs so that the users can get to know it's working well?

**Comment by connertennery** [comment]
Hi @beviz! There might be a slight problem with the starting directory. This is purely a guess, but it could be worth a shot.

Try renaming `Export-3c2c8378-eb74-4a84-b82b-1a8ca3706768` to just `Export` or something else that's a bit shorter. Let me know if that worked out for you. :)

I'll create an issue for verbose logging.

Thank you!

**Comment by connertennery** [comment]
@beviz I updated the script so grab a new copy and give it a shot. Logging can be enabled by using the `-v` arg when running. You can add verbosity by using `-vv` or `-vvv`.

**Comment by beviz** [comment]
@connertennery thanks for your prompt response. Let me have a try.
