### ISSUE TITLE
LinkText should be decoded always

### ISSUE THREAD

**Issue by yshalsager** [connertennery/Notion-to-Obsidian-Converter#28]
Pages' links are in languages that are written in non-ascii characters should be decoded in order to appear in the correct way.

For example, a link that is written in Arabic, and should be shown as `كتابة 50 تدوينة خلال السنة` is shown as `%D9%83%D8%AA%D8%A7%D8%A8%D8%A9%2050%20%D8%AA%D8%AF%D9%88%D9%8A%D9%86%D8%A9%20%D8%AE%D9%84%D8%A7%D9%84%20%D8%A7%D9%84%D8%B3%D9%86%D8%A9`.

This can be fixed easily be using `decodeURI` JavaScript's method.

**Comment by connertennery** [comment]
@yshalsager Thanks for submitting your issue, the example of Arabic, and the fix! I'll try to have the change merged in soon.

**Comment by connertennery** [comment]
@yshalsager Would you mind giving this another test and letting me know if it's properly fixed? Thank you! :heart:
