### ISSUE TITLE
Thank you so much :)

### ISSUE THREAD

**Issue by SudoCorentin** [connertennery/Notion-to-Obsidian-Converter#32]
Hello Conner and contributors - thank you so much! I hope you'll forgive me for clogging the system with another issue, it's just the simplest way I found to drop a word of gratitude for you having taken the time to build it and share it with the world. It worked like a charm. Thank yoU!

**Comment by connertennery** [comment]
@SudoCorentin Thank you for your kind words! I'm glad you found this little tool useful. :)
