### ISSUE TITLE
Support Unix-style paths

### ISSUE THREAD

**Issue by b3u** [connertennery/Notion-to-Obsidian-Converter#5]
Unix machines use `folder/folder2` instead of `folder\folder2`, so the links break on Unix. Maybe the [path module](https://nodejs.org/api/path.html) would be useful here.

**Comment by b3u** [comment]
never mind.

**Comment by connertennery** [comment]
Thank you for making the issue and closing it, @b3u! Someone else just emailed me about this earlier today and I had to wait for a break in work to fix it.

**Comment by b3u** [comment]
@connertennery You're very welcome. I changed the script myself, but forgot that I did that. It worked, so I thought I had been confused when I made the issue! That's why I closed it originally.

**Comment by connertennery** [comment]
Glad to hear it's working! I don't have a Linux distro up at the moment for testing. I should have made an issue when I got the email to avoid confusing. Next time I'll try to be better about that.

Don't hesitate to make more issues for bugs or features! This was originally going to be a quick, messy script, but I may rewrite it in TypeScript and maybe the Obsidian devs can fold it in.
