### ISSUE TITLE
Characters "omd" are converted to "[[]]"

### ISSUE THREAD

**Issue by block6791** [connertennery/Notion-to-Obsidian-Converter#7]
The string omd is converted into [[]]. In some languages, this string is used in normal words. For example, in my language the word "omdat" is converted into "[[]]at". 

I fixed this by replacing the characters omd into 1o2m3d in my original export, let main.js do its work, and replace 1o2m3d into omd afterwards.

**Comment by connertennery** [comment]
@block6791 Thanks for bringing this to my attention. I'll try to get it fixed soon if there's no pull request before I address it. Work is really busy so I can't devote as much time to patching this and converting it to TS as I had hoped.

**Comment by connertennery** [comment]
Need to verify this but I think the issue is line 41. It matches all text that ends with `md` instead of `.md`
Changing it to the following may be the fix.
`const linkFloaterMatches = content.match(/([\S]*\.md(\))?)/gi);`

**Comment by block6791** [comment]
I replaced line 41 with your suggested line and used it on the same files as yesterday. It works. The word "Omdat" is now as it was. And otherwise the conversion still works as expected on first glance.

**Comment by connertennery** [comment]
Glad to hear it worked for you. I had to change another line further down where it does the replace, but I've committed it so now everything should be good.
